package net.primal.domain.feeds

data class AdvancedSearchParsedQuery(
    val includes: String,
    val excludes: String,
    val hashtags: String,
    val kind: String,
    val postedBy: List<String>,
    val replyingTo: List<String>,
    val zappedBy: List<String>,
    val timeframe: String,
    val customTimeframeSince: String,
    val customTimeframeUntil: String,
    val scope: String,
    val sortBy: String,
    val orientation: String,
    val minWords: Int,
    val maxWords: Int,
    val minDuration: Int,
    val maxDuration: Int,
    val minScore: Int,
    val minInteractions: Int,
    val minLikes: Int,
    val minZaps: Int,
    val minReplies: Int,
    val minReposts: Int,
    val following: List<String>,
    val userMentions: List<String>,
    val sentiment: String,
)
