package net.primal.domain.wallet

data class WalletTransaction(
    val id: String,
    val walletLightningAddress: String,
    val type: TxType,
    val state: TxState,
    val createdAt: Long,
    val updatedAt: Long,
    val completedAt: Long?,
    val amountInBtc: Double,
    val amountInUsd: Double?,
    val isZap: Boolean,
    val isStorePurchase: Boolean,
    val userId: String,
    val userSubWallet: SubWallet,
    val userLightningAddress: String?,
    val otherUserId: String?,
    val otherLightningAddress: String?,
    val note: String?,
    val invoice: String?,
    val totalFeeInBtc: String?,
    val exchangeRate: String?,
    val onChainAddress: String?,
    val onChainTxId: String?,
    val zapNoteId: String?,
    val zapNoteAuthorId: String?,
    val zappedByUserId: String?,
)
