package net.primal.android.wallet.activation.regions

val WalletRegionJson = """
{
    "countries": [
        [
            "United States of America",
            "US"
        ],
        [
            "Afghanistan",
            "AF"
        ],
        [
            "Albania",
            "AL"
        ],
        [
            "Algeria",
            "DZ"
        ],
        [
            "Andorra",
            "AD"
        ],
        [
            "Angola",
            "AO"
        ],
        [
            "Antigua and Barbuda",
            "AG"
        ],
        [
            "Argentina",
            "AR"
        ],
        [
            "Armenia",
            "AM"
        ],
        [
            "Australia",
            "AU"
        ],
        [
            "Austria",
            "AT"
        ],
        [
            "Azerbaijan",
            "AZ"
        ],
        [
            "Bahrain",
            "BH"
        ],
        [
            "Bangladesh",
            "BD"
        ],
        [
            "Barbados",
            "BB"
        ],
        [
            "Belarus",
            "BY"
        ],
        [
            "Belgium",
            "BE"
        ],
        [
            "Belize",
            "BZ"
        ],
        [
            "Benin",
            "BJ"
        ],
        [
            "Bhutan",
            "BT"
        ],
        [
            "Bolivia",
            "BO"
        ],
        [
            "Bosnia and Herzegovina",
            "BA"
        ],
        [
            "Botswana",
            "BW"
        ],
        [
            "Brazil",
            "BR"
        ],
        [
            "Brunei",
            "BN"
        ],
        [
            "Bulgaria",
            "BG"
        ],
        [
            "Burkina Faso",
            "BF"
        ],
        [
            "Burundi",
            "BI"
        ],
        [
            "Cambodia",
            "KH"
        ],
        [
            "Cameroon",
            "CM"
        ],
        [
            "Canada",
            "CA"
        ],
        [
            "Cape Verde",
            "CV"
        ],
        [
            "Central African Republic",
            "CF"
        ],
        [
            "Chad",
            "TD"
        ],
        [
            "Chile",
            "CL"
        ],
        [
            "Colombia",
            "CO"
        ],
        [
            "Comoros",
            "KM"
        ],
        [
            "Costa Rica",
            "CR"
        ],
        [
            "Croatia",
            "HR"
        ],
        [
            "Cuba",
            "CU"
        ],
        [
            "Cyprus",
            "CY"
        ],
        [
            "Czech Republic",
            "CZ"
        ],
        [
            "Democratic Republic of the Congo",
            "CD"
        ],
        [
            "Denmark",
            "DK"
        ],
        [
            "Djibouti",
            "DJ"
        ],
        [
            "Dominica",
            "DM"
        ],
        [
            "Dominican Republic",
            "DO"
        ],
        [
            "East Timor",
            "TL"
        ],
        [
            "Ecuador",
            "EC"
        ],
        [
            "Egypt",
            "EG"
        ],
        [
            "El Salvador",
            "SV"
        ],
        [
            "Equatorial Guinea",
            "GQ"
        ],
        [
            "Eritrea",
            "ER"
        ],
        [
            "Estonia",
            "EE"
        ],
        [
            "Eswatini",
            "SZ"
        ],
        [
            "Ethiopia",
            "ET"
        ],
        [
            "Federated States of Micronesia",
            "FM"
        ],
        [
            "Fiji",
            "FJ"
        ],
        [
            "Finland",
            "FI"
        ],
        [
            "France",
            "FR"
        ],
        [
            "Gabon",
            "GA"
        ],
        [
            "Georgia",
            "GE"
        ],
        [
            "Germany",
            "DE"
        ],
        [
            "Ghana",
            "GH"
        ],
        [
            "Greece",
            "GR"
        ],
        [
            "Grenada",
            "GD"
        ],
        [
            "Guatemala",
            "GT"
        ],
        [
            "Guinea",
            "GN"
        ],
        [
            "Guinea-Bissau",
            "GW"
        ],
        [
            "Guyana",
            "GY"
        ],
        [
            "Haiti",
            "HT"
        ],
        [
            "Honduras",
            "HN"
        ],
        [
            "Hungary",
            "HU"
        ],
        [
            "Iceland",
            "IS"
        ],
        [
            "India",
            "IN"
        ],
        [
            "Indonesia",
            "ID"
        ],
        [
            "Iran",
            "IR"
        ],
        [
            "Iraq",
            "IQ"
        ],
        [
            "Israel",
            "IL"
        ],
        [
            "Italy",
            "IT"
        ],
        [
            "Ivory Coast",
            "CI"
        ],
        [
            "Jamaica",
            "JM"
        ],
        [
            "Japan",
            "JP"
        ],
        [
            "Jordan",
            "JO"
        ],
        [
            "Kazakhstan",
            "KZ"
        ],
        [
            "Kenya",
            "KE"
        ],
        [
            "Kingdom of the Netherlands",
            "NL"
        ],
        [
            "Kiribati",
            "KI"
        ],
        [
            "Kuwait",
            "KW"
        ],
        [
            "Kyrgyzstan",
            "KG"
        ],
        [
            "Laos",
            "LA"
        ],
        [
            "Latvia",
            "LV"
        ],
        [
            "Lebanon",
            "LB"
        ],
        [
            "Lesotho",
            "LS"
        ],
        [
            "Liberia",
            "LR"
        ],
        [
            "Libya",
            "LY"
        ],
        [
            "Liechtenstein",
            "LI"
        ],
        [
            "Lithuania",
            "LT"
        ],
        [
            "Luxembourg",
            "LU"
        ],
        [
            "Madagascar",
            "MG"
        ],
        [
            "Malawi",
            "MW"
        ],
        [
            "Malaysia",
            "MY"
        ],
        [
            "Maldives",
            "MV"
        ],
        [
            "Mali",
            "ML"
        ],
        [
            "Malta",
            "MT"
        ],
        [
            "Marshall Islands",
            "MH"
        ],
        [
            "Mauritania",
            "MR"
        ],
        [
            "Mauritius",
            "MU"
        ],
        [
            "Mexico",
            "MX"
        ],
        [
            "Moldova",
            "MD"
        ],
        [
            "Monaco",
            "MC"
        ],
        [
            "Mongolia",
            "MN"
        ],
        [
            "Montenegro",
            "ME"
        ],
        [
            "Morocco",
            "MA"
        ],
        [
            "Mozambique",
            "MZ"
        ],
        [
            "Myanmar",
            "MM"
        ],
        [
            "Namibia",
            "NA"
        ],
        [
            "Nauru",
            "NR"
        ],
        [
            "Nepal",
            "NP"
        ],
        [
            "New Caledonia",
            "NC"
        ],
        [
            "New Zealand",
            "NZ"
        ],
        [
            "Nicaragua",
            "NI"
        ],
        [
            "Niger",
            "NE"
        ],
        [
            "Nigeria",
            "NG"
        ],
        [
            "North Korea",
            "KP"
        ],
        [
            "North Macedonia",
            "MK"
        ],
        [
            "Norway",
            "NO"
        ],
        [
            "Oman",
            "OM"
        ],
        [
            "Pakistan",
            "PK"
        ],
        [
            "Palau",
            "PW"
        ],
        [
            "Panama",
            "PA"
        ],
        [
            "Papua New Guinea",
            "PG"
        ],
        [
            "Paraguay",
            "PY"
        ],
        [
            "People's Republic of China",
            "CN"
        ],
        [
            "Peru",
            "PE"
        ],
        [
            "Philippines",
            "PH"
        ],
        [
            "Poland",
            "PL"
        ],
        [
            "Portugal",
            "PT"
        ],
        [
            "Qatar",
            "QA"
        ],
        [
            "Republic of Ireland",
            "IE"
        ],
        [
            "Republic of the Congo",
            "CG"
        ],
        [
            "Romania",
            "RO"
        ],
        [
            "Russia",
            "RU"
        ],
        [
            "Rwanda",
            "RW"
        ],
        [
            "Saint Kitts and Nevis",
            "KN"
        ],
        [
            "Saint Lucia",
            "LC"
        ],
        [
            "Saint Vincent and the Grenadines",
            "VC"
        ],
        [
            "Samoa",
            "WS"
        ],
        [
            "San Marino",
            "SM"
        ],
        [
            "Saudi Arabia",
            "SA"
        ],
        [
            "Senegal",
            "SN"
        ],
        [
            "Serbia",
            "RS"
        ],
        [
            "Seychelles",
            "SC"
        ],
        [
            "Sierra Leone",
            "SL"
        ],
        [
            "Singapore",
            "SG"
        ],
        [
            "Slovakia",
            "SK"
        ],
        [
            "Slovenia",
            "SI"
        ],
        [
            "Solomon Islands",
            "SB"
        ],
        [
            "Somalia",
            "SO"
        ],
        [
            "South Africa",
            "ZA"
        ],
        [
            "South Korea",
            "KR"
        ],
        [
            "South Sudan",
            "SS"
        ],
        [
            "Spain",
            "ES"
        ],
        [
            "Sri Lanka",
            "LK"
        ],
        [
            "State of Palestine",
            "PS"
        ],
        [
            "Sudan",
            "SD"
        ],
        [
            "Suriname",
            "SR"
        ],
        [
            "Sweden",
            "SE"
        ],
        [
            "Switzerland",
            "CH"
        ],
        [
            "Syria",
            "SY"
        ],
        [
            "São Tomé and Príncipe",
            "ST"
        ],
        [
            "Taiwan",
            "TW"
        ],
        [
            "Tajikistan",
            "TJ"
        ],
        [
            "Tanzania",
            "TZ"
        ],
        [
            "Thailand",
            "TH"
        ],
        [
            "The Bahamas",
            "BS"
        ],
        [
            "The Gambia",
            "GM"
        ],
        [
            "Togo",
            "TG"
        ],
        [
            "Tonga",
            "TO"
        ],
        [
            "Trinidad and Tobago",
            "TT"
        ],
        [
            "Tunisia",
            "TN"
        ],
        [
            "Turkey",
            "TR"
        ],
        [
            "Turkmenistan",
            "TM"
        ],
        [
            "Tuvalu",
            "TV"
        ],
        [
            "Uganda",
            "UG"
        ],
        [
            "Ukraine",
            "UA"
        ],
        [
            "United Arab Emirates",
            "AE"
        ],
        [
            "United Kingdom",
            "GB"
        ],
        [
            "Uruguay",
            "UY"
        ],
        [
            "Uzbekistan",
            "UZ"
        ],
        [
            "Vanuatu",
            "VU"
        ],
        [
            "Vatican City",
            "VA"
        ],
        [
            "Venezuela",
            "VE"
        ],
        [
            "Vietnam",
            "VN"
        ],
        [
            "Yemen",
            "YE"
        ],
        [
            "Zambia",
            "ZM"
        ],
        [
            "Zimbabwe",
            "ZW"
        ]
    ],
    "states": [
        [
            "Alabama",
            "US-AL"
        ],
        [
            "Alaska",
            "US-AK"
        ],
        [
            "Arizona",
            "US-AZ"
        ],
        [
            "Arkansas",
            "US-AR"
        ],
        [
            "California",
            "US-CA"
        ],
        [
            "Colorado",
            "US-CO"
        ],
        [
            "Connecticut",
            "US-CT"
        ],
        [
            "D.C.",
            "US-DC"
        ],
        [
            "Delaware",
            "US-DE"
        ],
        [
            "Florida",
            "US-FL"
        ],
        [
            "Georgia",
            "US-GA"
        ],
        [
            "Hawaii",
            "US-HI"
        ],
        [
            "Idaho",
            "US-ID"
        ],
        [
            "Illinois",
            "US-IL"
        ],
        [
            "Indiana",
            "US-IN"
        ],
        [
            "Iowa",
            "US-IA"
        ],
        [
            "Kansas",
            "US-KS"
        ],
        [
            "Kentucky",
            "US-KY"
        ],
        [
            "Louisiana",
            "US-LA"
        ],
        [
            "Maine",
            "US-ME"
        ],
        [
            "Maryland",
            "US-MD"
        ],
        [
            "Massachusetts",
            "US-MA"
        ],
        [
            "Michigan",
            "US-MI"
        ],
        [
            "Minnesota",
            "US-MN"
        ],
        [
            "Mississippi",
            "US-MS"
        ],
        [
            "Missouri",
            "US-MO"
        ],
        [
            "Montana",
            "US-MT"
        ],
        [
            "Nebraska",
            "US-NE"
        ],
        [
            "Nevada",
            "US-NV"
        ],
        [
            "New Hampshire",
            "US-NH"
        ],
        [
            "New Jersey",
            "US-NJ"
        ],
        [
            "New Mexico",
            "US-NM"
        ],
        [
            "New York",
            "US-NY"
        ],
        [
            "North Carolina",
            "US-NC"
        ],
        [
            "North Dakota",
            "US-ND"
        ],
        [
            "Ohio",
            "US-OH"
        ],
        [
            "Oklahoma",
            "US-OK"
        ],
        [
            "Oregon",
            "US-OR"
        ],
        [
            "Pennsylvania",
            "US-PA"
        ],
        [
            "Puerto Rico",
            "US-PR"
        ],
        [
            "Rhode Island",
            "US-RI"
        ],
        [
            "South Carolina",
            "US-SC"
        ],
        [
            "South Dakota",
            "US-SD"
        ],
        [
            "Tennessee",
            "US-TN"
        ],
        [
            "Texas",
            "US-TX"
        ],
        [
            "Utah",
            "US-UT"
        ],
        [
            "Vermont",
            "US-VT"
        ],
        [
            "Virginia",
            "US-VA"
        ],
        [
            "Washington",
            "US-WA"
        ],
        [
            "West Virginia",
            "US-WV"
        ],
        [
            "Wisconsin",
            "US-WI"
        ],
        [
            "Wyoming",
            "US-WY"
        ]
    ]
}
""".trimIndent()
