name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache gradle
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Unpack secrets
      run: |
        openssl base64 -d -out app/src/aosp/google-services.json <<< "${{ secrets.GOOGLE_SERVICES_FLAVOR_AOSP }}"
        openssl base64 -d -out app/src/google/google-services.json <<< "${{ secrets.GOOGLE_SERVICES_FLAVOR_GOOGLE }}"

    - name: Check detekt
      run: ./gradlew detekt

    - name: Check lint
      run: ./gradlew lint

    - name: Run tests on AOSP flavour
      run: ./gradlew testAospDebugUnitTest

    - name: Compile AOSP debug build to verify no-compilation errors
      run: ./gradlew compileAospDebugKotlin

    - name: Compile Google debug build to verify no-compilation errors
      run: ./gradlew compileGoogleDebugKotlin