name: "Manual: Publish latest release to Zapstore"

on:
  workflow_dispatch:
    inputs:
      zsp-version:
        description: "zsp version to be used to publish the event"
        required: true
        default: '0.4.3'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download & install zsp
        run: |
          DOWNLOAD_URL="https://github.com/zapstore/zsp/releases/download/v${{ github.event.inputs.zsp-version }}/zsp-${{ github.event.inputs.zsp-version }}-linux-amd64"
          curl -fsSL "$DOWNLOAD_URL" -o zsp
          sudo chmod +x zsp
          sudo mv zsp /usr/local/bin/zsp

      - name: Publish to Zapstore
        env:
          SIGN_WITH: ${{ secrets.ZAPSTORE_SIGN_WITH }}
        run: zsp publish -q
