name: "Manual: Publish to Zapstore"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The git tag or ref to publish"
        required: true
      zsp-version:
        description: "zsp version to use for publishing"
        required: true
        default: "0.4.2"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out at specified tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Download & install zsp
        run: |
          DOWNLOAD_URL="https://github.com/zapstore/zsp/releases/download/v${{ github.event.inputs.zsp-version }}/zsp-${{ github.event.inputs.zsp-version }}-linux-amd64"
          curl -fsSL "$DOWNLOAD_URL" -o zsp
          sudo chmod +x zsp
          sudo mv zsp /usr/local/bin/zsp

      - name: Publish to Zapstore
        env:
          SIGN_WITH: ${{ secrets.ZAPSTORE_SIGN_WITH }}
        run: zsp publish
