name: Build Android Project
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          sdk-version: '31'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew


      - name: Build Android project
        run: ./gradlew assembleDebug
