name: Create release from tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build, sign and upload artifact
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Unpack Config file
      run:  openssl base64 -d -out config.properties <<< "${{ secrets.CONFIG_PROPERTIES }}"

    - name: Unpack Certificates
      run: |
        openssl base64 -d -out app/primal_alternative_android.jks <<< "${{ secrets.CERT_ALTERNATIVE }}"
        openssl base64 -d -out app/primal_googlePlay_android.jks <<< "${{ secrets.CERT_PLAYSTORE }}"

    - name: Build apks
      run: ./gradlew assembleReleaseAlternative --no-daemon

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: primal-${{ github.ref_name }}.apk
        path: app/build/outputs/apk/releaseAlternative/*apk

    - name: Zip R8 mapping file
      run: zip primal-${{ github.ref_name }}-mapping.zip app/build/outputs/mapping/releaseAlternative/mapping.txt

    - name: Upload R8 mapping file
      uses: actions/upload-artifact@v3
      with:
        name: primal-${{ github.ref_name }}-mapping.zip
        path: primal-${{ github.ref_name }}-mapping.zip

  release:
   name: Create GitHub release
   needs: build
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Download APK artifact
     uses: actions/download-artifact@v1
     with:
       name: primal-${{ github.ref_name }}.apk

   - name: Download APK artifact
     uses: actions/download-artifact@v1
     with:
       name: primal-${{ github.ref_name }}-mapping.zip

   - name: Create Release
     id: create_release
     uses: softprops/action-gh-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       tag_name: ${{ github.ref_name }}
       name: Primal ${{ github.ref_name }}
       draft: true
       prerelease: true
       body_path: RELEASE_NOTES.md
       files: |
         primal-${{ github.ref_name }}.apk
         primal-${{ github.ref_name }}-mapping.zip
