name: Create release from tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build, sign and upload artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Unpack Config file
      run:  openssl base64 -d -out config.properties <<< "${{ secrets.CONFIG_PROPERTIES }}"

    - name: Unpack Certificates
      run: |
        openssl base64 -d -out app/primal_alternative_android.jks <<< "${{ secrets.CERT_ALTERNATIVE }}"
        openssl base64 -d -out app/primal_googlePlay_android.jks <<< "${{ secrets.CERT_PLAYSTORE }}"

    - name: Build & Prepare APK artifacts
      run: |
        ./gradlew assembleReleaseAlternative --no-daemon
        mv app/build/outputs/apk/releaseAlternative/*apk primal-${{ github.ref_name }}.apk
        zip -j primal-${{ github.ref_name }}-mapping.zip app/build/outputs/mapping/releaseAlternative/mapping.txt

    - name: Upload APK artifacts to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: primal-${{ github.ref_name }}
        path: |
          primal-${{ github.ref_name }}.apk
          primal-${{ github.ref_name }}-mapping.zip

    - name: Build & Upload bundle to Google Play
      run: ./gradlew publishReleasePlayStoreBundle --track alpha --release-name "${{ github.ref_name }}"

  release:
   name: Create GitHub release
   needs: build
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Download artifacts
     uses: actions/download-artifact@v1
     with:
       name: primal-${{ github.ref_name }}

   - name: Create Release
     id: create_release
     uses: softprops/action-gh-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       tag_name: ${{ github.ref_name }}
       name: Primal ${{ github.ref_name }}
       draft: true
       prerelease: true
       body_path: app/src/release/github/release-notes/github.md
       files: primal-${{ github.ref_name }}/*
