name: Create release from tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build, sign and upload artifact
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: GitHub Tag Name example
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{ github.ref_name }}"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build apks
      run: ./gradlew build --no-daemon

    # Fetched https://github.com/marketplace/actions/sign-android-release
    # Dont forget to add variables to keystore
    - name: sign apk
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref_name }}
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

  release:
   name: Create github release and attach apk
   needs: build
   runs-on: ubuntu-latest
   steps:
   - name: Download APK from build
     uses: actions/download-artifact@v1
     with:
       name: ${{ github.ref_name }}
   # GITHUB_TOKEN is provided in action, you need to add write permissions in action settings
   - name: Create Release
     id: create_release
     uses: softprops/action-gh-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       tag_name: ${{ github.ref_name }}
       name: Release ${{ github.ref_name }}
       draft: false
       prerelease: false
       files: ${{ github.ref_name }}/*